modLoader="javafml"
loaderVersion="[41,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TwelveIterationMods/balm-mod/issues"

[[mods]]
modId="balmtemplate"
version="${file.jarVersion}"
displayName="Balm Template Mod"
displayURL="https://blay09.net/mods/balm"
logoFile="balmtemplate-icon.png"
credits="BlayTheNinth"
authors="BlayTheNinth"
description='''
'''

[[dependencies.balmtemplate]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.balmtemplate]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.balmtemplate]]
    modId="balm"
    mandatory=true
    versionRange="[4.3.0,)"
    ordering="NONE"
    side="BOTH"
