name: update-versions
on:
  workflow_dispatch:
    inputs:
      minecraftVersion:
        description: 'The Minecraft version to update to'
        required: true
        type: string
      channel:
        description: 'The release channel to update to, either latest or recommended'
        required: false
        default: 'latest'
        type: choice
        options:
          - latest
          - recommended

jobs:
  update-versions:
    uses: ModdingForBlockheads/Workflows/.github/workflows/update-versions.yml@main
    with:
      minecraftVersion: ${{ github.event.inputs.minecraftVersion }}
      channel: ${{ github.event.inputs.channel }}
    secrets: inherit